### ISSUE TITLE
Add additional VM configuration options

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#36]
Currently it's already possible to specify essential VM parameters such as CPUs, memory, disk size, and storage class for the VM disk. We should be able to specify also additional VM parameters, usually for an enhanced VM performance. These could include, among others:

* [hugepages support](https://kubevirt.io/user-guide/#/installation/hugepages)
* [dedicated CPU](https://kubevirt.io/user-guide/#/creation/dedicated-cpu)
* [disk device cache](https://kubevirt.io/user-guide/#/creation/disks-and-volumes?id=disk-device-cache)

We should discuss what additional parameters should be added, and how should they be configured. The options are:

* In the `spec.providerConfig` section of the cloud profile, if to configure machine types shared between multiple shoots
* In the `provider.workers[n].providerConfig` section of the shoot resource, to configure individual shoots.

/area performance
/kind enhancement
/priority normal
/platform kubevirt

**Comment by mfranczy** [comment]
- support for resource over-commit https://kubevirt.io/user-guide/#/usage/overcommit

- high performance options for disks and volumes https://kubevirt.io/user-guide/#/creation/disks-and-volumes?id=high-performance-features (IOThreads, Virtio Block Multi-Queue, DiskDevice cache which is mentioned alredy) 

- support for VM run strategies https://kubevirt.io/user-guide/#/creation/run-strategies

- set liveness and readiness probes https://kubevirt.io/user-guide/#/creation/probes

**Comment by mfranczy** [comment]
@stoyanr  @moadqassem  we have to discuss how we want to support requests and limits in terms of specified resources. Currently in a `machineType` object we can only set requested resources, the question is how we want to handle limits. 
Let's discuss this on our daily sync.

**Comment by mfranczy** [comment]
PR in mcm created as well https://github.com/gardener/machine-controller-manager-provider-kubevirt/pull/20/files

**Comment by mfranczy** [comment]
@stoyanr I removed support for `RunStrategy` and probes, giving this a second thought, since MCM has a timeout for machine to join nodes that would bring another complexity level for MCM-provider-kubevirt which is not needed.
