### ISSUE TITLE
Add optional dev setups

### ISSUE THREAD

**Issue by mfranczy** [gardener/gardener-extension-provider-kubevirt#43]
In the current state it's required to run GCP provider in order to have GCP k8s cluster, it brings additional complexity level. I would suggest to create k8s cluster on GCP with nested virtualization enabled by using KubeOne (thanks @moadqassem ). We should keep it as seed and provider cluster (to avoid having complex environment). It's very hard for new users to follow the installation steps as it requires deeper gardener knowledge, we should keep it as simple as possible with clear instruction what should be done.

**Comment by mfranczy** [comment]
For gcp we should use KubeVirt >= 0.32 as it contains GCP bugfix for qemu-kvm

**Comment by mfranczy** [comment]
I've created alternative setup which is simpler in my opinion, let's sync on that on Monday.

**Comment by mfranczy** [comment]
as we discussed today with @stoyan  I will add optional dev setups instead of replacing the one which is already created

**Comment by stoyanr** [comment]
As discussed, I am closing this since it's not very important at this point.
