### ISSUE TITLE
Add the shoot cluster name in the KubeVirt provider spec.

### ISSUE THREAD

**Issue by moadqassem** [gardener/gardener-extension-provider-kubevirt#45]
At the moment, the VMs which are created in the kubevirt cluster can potentially have the same name within the same namespace which would result some conflicting operations across different shoot clusters. To solve this issue, we would add labels on each created vm which contains the name of the shoot, that is responsible for the specified vm. 

There is already a [ticket](https://github.com/gardener/machine-controller-manager-provider-kubevirt/issues/11) in the kubevirt mc, which should address this issue, however, it is not possible to have an access on the shoot cluster name from the machine controller directly. A potential solution to overcome this issue is, adding a field in the [KubeVirtProviderSpec](https://github.com/gardener/machine-controller-manager-provider-kubevirt/blob/master/pkg/kubevirt/apis/provider_spec.go#L18) that specifies the name of the shoot cluster. 

```go
ShootClusterName string `json:"shootClusterName,omitempty"`
```

**Comment by stoyanr** [comment]
The cluster name is already there, in the `mcm.gardener.cloud/cluster` tag, see https://github.com/gardener/gardener-extension-provider-kubevirt/blob/2b961756ecb7bb66a1d1d21c98cda5db7fe3c86a/pkg/controller/worker/machines.go#L134. As discussed, closing the issue.
