### ISSUE TITLE
Avoid DNS loop on Kubevirt VMs when using node-local-dns

### ISSUE THREAD

**Issue by mfranczy** [gardener/gardener-extension-provider-kubevirt#50]
DNS is being copied to VM from the pod that means if underlaying cluster and overlaying cluster are using node-local-dns then we will have a DNS loop. To solve the problem we have to support DNS settings for VM.

**Comment by mfranczy** [comment]
related to https://github.com/gardener/gardener-extension-provider-kubevirt/issues/36

**Comment by stoyanr** [comment]
@mfranczy I am not seeing DNS loop issues in shoots that have been successfully reconciled. 
* What does it mean for a cluster to use node-local-dns? Is it what's described in https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/, or is it something slightly different you have in mind?
* How to cause Gardener to use node-local-dns when creating a shoot? This doesn't seem to be the default. Or is this something the user sets up manually after a shoot has been created.
* What exactly DNS settings should be supported?

**Comment by mfranczy** [comment]
> What does it mean for a cluster to use node-local-dns? Is it what's described in https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/, or is it something slightly different you have in mind?

yes this is cache

> How to cause Gardener to use node-local-dns when creating a shoot? This doesn't seem to be the default. Or is this something the user sets up manually after a shoot has been created.

it's not visible always, it depends how k8s cluster was created and if uses node-local-dns, KubeVirt copies resolv.conf from the pod.

> What exactly DNS settings should be supported?

The same options and policies that are available for pods
https://kubevirt.io/user-guide/#/usage/dns
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-hostname-and-subdomain-fields

**Comment by mfranczy** [comment]
as we spoke we should add small change in mcm-provider-kubevirt

> As a side remark, I don't like that DNSConfig is passed as a JSON string in https://github.com/gardener/machine-controller-manager-provider-kubevirt/blob/f3600b1f2296f4df617817f8a67100b96bc4266b/pkg/kubevirt/apis/provider_spec.go#L32, and then unmarshalled from JSON in the code. I would much prefer to use the proper type corev1.PodDNSConfig there as well, and to ensure that the YAML in the machineclass conforms to that type so that it's unmarshalled implicitly.

**Comment by mfranczy** [comment]
mcm-provider-kubevirt pr just for reference https://github.com/gardener/machine-controller-manager-provider-kubevirt/pull/19
