### ISSUE TITLE
MCM RBAC charts are not applied for shoot

### ISSUE THREAD

**Issue by mfranczy** [gardener/gardener-extension-provider-kubevirt#52]
Currently, RBAC charts https://github.com/gardener/gardener-extension-provider-kubevirt/tree/master/charts/internal/machine-controller-manager/shoot are not applied for the shoot cluster this blocks mcm to start tasks.

**Comment by stoyanr** [comment]
@mfranczy I do see these RBAC resources in all shoots that have been successfully reconciled. As you mention, without them MCM would not be able to do its job, so the reconciliation could not finish successfully in the first place. So what you are reporting is not a general issue, but something related to a particular test setup or condition. Please dig deeper and describe this in detail.

**Comment by mfranczy** [comment]
@stoyanr did you use the lastest mcm? I will dig into this but I would expect that when I deploy mcm I would have these charts applied, how custom setup can influence this?

**Comment by moadqassem** [comment]
@mfranczy Any updates regarding this? as I am also seeing that the extension is not able to access any resources due to lack of rbacs

**Comment by mfranczy** [comment]
@moadqassem unfortunately due to networking debug sessions last week I was not able to proceed with that, as soon as I know something more I will update this issue.

**Comment by moadqassem** [comment]
```shell
E0917 15:33:27.819468       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:machine-controller-manager" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E0917 15:33:30.825614       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:machine-controller-manager" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E0917 15:33:30.827435       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: nodes is forbidden: User "system:machine-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope

```

**Comment by stoyanr** [comment]
@moadqassem Please add some more detail or give me access to a setup in which it's reproducible. Just adding the error is not enough, since I didn't reproduce it even a single time in the dozens of tests I did on several different test setups (both GCP and OpenShift based)

**Comment by mfranczy** [comment]
Closing the issue, I was not able to reproduce it again, most likely I was using some old image in the past. If this will occur again I will re-open it.
