### ISSUE TITLE
Rename "dontUsePreAllocatedDataVolumes" to not have "dont" in it

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener-extension-provider-kubevirt#65]
I would suggest to change the field to `useDynamicallyAllocatedDataVolumes` or something similar. Having `dont` in the name makes it harder to understand if setting it to `true` or `false` actually does (double negative).

**Comment by stoyanr** [comment]
@mvaldev Thanks for your feedback, I agree. We just need to figure out the right naming for this option. @mfranczy @mmoath does `useDynamicallyAllocatedDataVolumes` sound correct or do you have other suggestions?

**Comment by mfranczy** [comment]
`useDynamicallyAllocatedDataVolumes` sounds good to me

**Comment by moadqassem** [comment]
SGTM

**Comment by mfranczy** [comment]
sorry I've read `usePreAllocatedDataVolumes` instead of `useDynamicallyAllocatedDataVolumes`, for me it would be more clear to have `disablePreAllocatedDataVolumes`.
